/** Costante con i testi da usare negli input */
export const INPUT_CONSTANT = {
  nome: 'Nome',
  cognome: 'Cognome',
  dataNascita: 'Data di nascita',
  luogoNascita: 'Luogo di nascita',
  citta: 'Citta',
  provincia: 'Provincia',
  indirizzo: 'Indirizzo',
  email: 'Email',
  telefono: 'Telefono',
  note: 'Note',
  username: 'Username',
  password: 'Password',
  elimina: 'Elimina',
  azioni_di_gruppo: 'Azioni di gruppo',
  ruolo: 'Ruolo',
  nome_cognome: 'Nome o Cognome',
  stato: 'Stato',
  ricerca: 'Ricerca',
  pageNumber: 0,
  pageSize: 10,
  tags: 'Tags',
  tag: 'Tag',
  descrizione: 'Descrizione',
  data_inizio: 'Data inizio',
  data_fine: 'Data fine',
  nome_e_cognome: 'Nome e cognome',
  email_recupero: 'Email di recupero',
  campi_obbligatori: '* Campi obbligatori',
  quantita: 'Quantità',
  costo: 'Costo',
  nome_prodotto: 'Nome prodotto',
  codice: 'Codice prodotto',
  tipologia: 'Tipologia',
  data: 'DATA ORDINE',
  id: 'ID ORDINE',

};

/** Costante con i testi da usare negli input di una tabella*/
export const TABLE_INPUT_CONSTANT = {
  username: 'Username',
  usertype: 'Ruolo',
  id: 'ID ORDINE',
  nome: 'NOME PRODOTTO',
  costo: 'PREZZO',
  tipologia: 'TIPOLOGIA',
  quantita: 'QUANTITA',
  data: 'DATA ACQUISTO'
};
