/** Costante con i testi di label generiche */
export const LABEL_CONSTANT = {
  visualizza : 'Visualizza',
  accedi: 'Accedi ora',
  login: 'Login',
  inserisci_credenziali: 'Inserisci le credenziali di accesso fornite.',
  no_account: 'Non hai un account?',
  ricordami: 'Ricordami',
  registrati: 'Registrati',
  inserisci_dati: 'Inserisci i tuoi dati e procedi con la registrazione',
  password_dimenticata: 'Password dimenticata?',
  errore_autenticazione: 'Autenticazione non riuscita',
  effettua_logout: 'Effettua Logout',
  conferma_logout: 'Sei sicuro di voler effettuare il logout?',
  profilo: 'Profilo',
  logout: 'Logout',
  indietro: 'INDIETRO',
  sicuro_di_uscire: 'Sei sicuro di uscire?',
  modifiche_non_salvate: 'Le modifiche apportate potrebbero non essere salvate',
  cambia_password: 'CAMBIA PASSWORD',
  cambio_password: 'Cambio Password',
  modifica_password: 'Modifica password',
  VAI_AL_PROFILO: 'Vai al profilo',
  Dettaglio_notifica: 'Apri Notifica',
  work_in_progress: 'WORK IN PROGRESS',
  delete_confirm: 'SICURO?',
  delete_dialog: "Una volta eliminato il profilo perderai l'account",
  delete_user: "Click su 'Elimina' l'operazione sarà definitiva",
  pagina_non_disponibile: 'La pagina alla quale stai cercando di accedere non è ancora disponibile',
  modifica: 'Modifica',
  elimina: 'Elimina',
  nuovo_utente: 'Aggiungi nuovo utente',
  informativa: 'Informativa Privacy',
  prodotto_creato: 'Prodotto creato con successo!',
  prodotto_creato_sub: 'Hai creato il tuo prodotto.',
  modifica_utente: 'Modifica i dati dell\'utente',
  profilo_creato:'Profilo creato!',
  profilo_creato_sub:'Account creato con successo.',
  back_login:'Ritorna alla login',
  info_generali:'Informazioni Generali',
  info_accesso:'Informazioni Accesso',
  gestione_account: 'Gestione Account',
  delete_profilo:'Puoi eliminare il tuo account e tutti i dati associati ad esso',
  modifica_profilo:'Profilo modificato con successo!',
  modifica_profilo_sub:'Hai modificato il tuo profilo',
  modifica_negozio:'Negozio modificato con successo!',
  modifica_negozio_sub:'Hai modificato il tuo negozio',
  success_delete_user: 'Utente eliminato con successo',
  campi_obligatori:'* Campi obligatori',
  campo_obligatorio:'* Campo obligatorio',
  campo_obligatorio_costo:'* Campo obligatorio, usare solo caratteri numerici',
  modifica_prodotto:'Prodotto modificato con successo!',
  modifica_prodotto_sub:'Hai modificato correttamente il tuo prodotto',
  eliminazione_prodotto:'Prodotto eliminato con successo!',
  eliminazione_prodotto_sub:'Hai eliminato correttamente il tuo prodotto',
  aggiunta_prodotto:'Prodotto aggiunto al carello!',
  nuovo_prodotto : 'Nuovo prodotto',
  update_prodotto : 'Modifica prodotto',
  autorizzazione : "Non sei autorizzato ad accederre a questa pagina",
};

/** Costante per la stringa da far visualizzare in caso di tabella vuota */
export const RESULT_CONSTANT = {
  nessun_risultato: 'Nessun risultato trovato.',
  nessun_contenuto: 'Nessun contenuto',
};
